tspdrv: dw7914: make buf_len a define instead of variable
../../../../../../kernel/lge/sm7250/drivers/tspdrv/dw7914/ImmVibeSPI.c:919:21: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
  919 |         char file_name_buf[buf_len];
      |                            ^~~~~~~

Change-Id: I42b934ab895f3c83f9788881e918188f72c82850
Signed-off-by: Han Sol Jin <hansol@hansol.ca>